version: '2'

services:

  rproxy:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/apache2/conf.d
      #- ./auth:/auth
      #- ./cert:/cert
